// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmRfjaSb7MjQ68xm-paku5gGTqBsVC1DI',
    appId: '1:117135591486:web:cb54d3c3a9311998d4696f',
    messagingSenderId: '117135591486',
    projectId: 'sadi-c04c5',
    authDomain: 'sadi-c04c5.firebaseapp.com',
    storageBucket: 'sadi-c04c5.appspot.com',
    measurementId: 'G-1LEDTWH037',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChMbjtLeMf97QEK-0vPI68K4Jz1VEwV3E',
    appId: '1:117135591486:android:7ad5dacdad199440d4696f',
    messagingSenderId: '117135591486',
    projectId: 'sadi-c04c5',
    storageBucket: 'sadi-c04c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwLlg6BCUO4YYv9sVqJhD02JsVZ_BPPDc',
    appId: '1:117135591486:ios:f44221c5f39940edd4696f',
    messagingSenderId: '117135591486',
    projectId: 'sadi-c04c5',
    storageBucket: 'sadi-c04c5.appspot.com',
    iosBundleId: 'com.example.sadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwLlg6BCUO4YYv9sVqJhD02JsVZ_BPPDc',
    appId: '1:117135591486:ios:64bf845696920f56d4696f',
    messagingSenderId: '117135591486',
    projectId: 'sadi-c04c5',
    storageBucket: 'sadi-c04c5.appspot.com',
    iosBundleId: 'com.example.sadi.RunnerTests',
  );
}
